version: "3"

vars:
  # Application
  ARTIFACT_ID: bzip
  VERSION: 0.1.0-SNAPSHOT
  MAIN_CLASS: "com.daromi.{{.ARTIFACT_ID}}.cli.Main"

  # Build
  BUILD_DIR: build
  CLASS_DIR: "{{.BUILD_DIR}}/classes"
  LIB_DIR: "{{.BUILD_DIR}}/lib"
  PKG_PATH: "{{.LIB_DIR}}/{{.ARTIFACT_ID}}-{{.VERSION}}.jar"

tasks:
  default:
    cmd: task -a

  clean:
    cmd: rm -rf {{.BUILD_DIR}}

  build:
    vars:
      SOURCE_DIR: src
    cmd: etc/jcp {{.SOURCE_DIR}} {{.CLASS_DIR}}

  build:run:
    deps:
      - build
    cmd: java -cp {{.CLASS_DIR}} {{.MAIN_CLASS}}

  package:
    deps:
      - build
    cmd: jar -c -f {{.PKG_PATH}} -e {{.MAIN_CLASS}} -C {{.CLASS_DIR}} .

  package:run:
    deps:
      - package
    cmd: java -jar {{.PKG_PATH}}
