version: "3"

vars:
  ARTIFACT_ID: bzip
  VERSION: 0.1.0
  MAIN_CLASS: com.daromi.bzip.Main

  BUILD_DIR: build
  CLASS_DIR: "{{.BUILD_DIR}}/classes"
  LIB_DIR: "{{.BUILD_DIR}}/lib"
  PKG_PATH: "{{.LIB_DIR}}/{{.ARTIFACT_ID}}-{{.VERSION}}.jar"

tasks:
  default:
    cmds:
      - task -a

  clean:
    cmds:
      - rm -rf {{.BUILD_DIR}}

  build:
    vars:
      SOURCE_DIR: src
    cmds:
      - dev/jcp {{.SOURCE_DIR}} {{.CLASS_DIR}}

  package:
    deps: [build]
    cmds:
      - jar -c -f {{.PKG_PATH}} -e {{.MAIN_CLASS}} -C {{.CLASS_DIR}} .

  build:run:
    deps: [build]
    cmds:
      - java -cp {{.CLASS_DIR}} {{.MAIN_CLASS}}

  package:run:
    deps: [package]
    cmds:
      - java -jar {{.PKG_PATH}}
