#!/bin/bash

usage() {
    echo >&2 "usage: jcp <source_dir> <dest_dir>"
    exit 64
}

readonly source_dir="$1"

if [[ -z "$source_dir" ]]; then
    echo >&2 "jcp: Missing source directory"
    usage
fi

if [[ ! -d "$source_dir" ]]; then
    echo >&2 "jcp: $source_dir: No such directory"
    usage
fi

readonly dest_dir="$2"

if [[ -z "$dest_dir" ]]; then
    echo >&2 "jcp: Missing dest directory"
    usage
fi

if [[ ! -d "$dest_dir" ]]; then
    mkdir "$dest_dir"
fi

find "$source_dir" -name '*.java' -exec javac {} -d "$dest_dir" \;

echo "jcp: compilation successful: Output in '$dest_dir'"
exit 0
